spring.application.name=ms-persona
server.port=8083

spring.r2dbc.url=r2dbc:mysql://localhost:3307/db_persona
spring.r2dbc.username=root
spring.r2dbc.password=root

external.bootcamp-service.url=http://localhost:8082

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
